---
- name: Install and configure nginx for static website hosting
  hosts: frontend
  become: yes

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
