---
- name: checking variable preference
  hosts: local
  connection: local

  vars:
    NAME: from play level

  # vars_files:
  #   - course.yaml

  # vars_prompt:
  #   - name: NAME
  #     prompt: "What is your NAME?"
  #     private: false

  tasks:
    - name: testing variables preference
      # vars:
      #   NAME: from task level
      ansible.builtin.debug:
        msg: "Name is: {{ NAME }}"


        #1st prefrence is command line aruguements
        #2nd prefrence is task level variables
        #3rd prefrence is files(course.yaml file)
        #4th prefrence is from prompt


