- name: datatypes
  hosts: local
  connection: local
  vars: 
    Course: "Deveops with aws"  #string
    Duration: 120 #number
    is_live: true #boolean
    # list
    tools: # ["linux","shell","ansible"]
    - "linux"
    - shell
    - ansible
    concepts: #dictonary or map
      cloud: aws
      cm: ansible
  tasks: 
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{Course}}, Duration is : {{Duration}}min, is it live: {{is_live}}, tools are : {{tools}}, and concepts are :{{concepts}}"




